### ISSUE TITLE
A html dom node exception is occurring all the time in the 1.27 version 

### ISSUE THREAD

**Issue by martinbedouret** [cboard-org/cboard#1475]
This exception is occurring all the time in the 1.27 version 
```
Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at chunk-R5WKEOII.js:118:1164
    at Array.forEach (<anonymous>)
    at gte (chunk-R5WKEOII.js:118:1149)
    at async Kc (chunk-R5WKEOII.js:21:87423)
    at async wi (chunk-R5WKEOII.js:118:1322)
(
 ```

**Comment by martinbedouret** [comment]
this was generated by a chrome extension on my local
